Repository gdgradzymin/ngPolandConfNext, pull requests merged in 2020-11, with the labels that each got.

#128 Fixed avatars in speakers and workshops
  lib/screens/presenter.dart
  lib/widgets/speakers/content.dart
  lib/widgets/workshops/content.dart
Labels: bug

#130 Corrected getters
  lib/providers/eventItems.dart
  lib/providers/infoItems.dart
  lib/providers/speakers.dart
  lib/providers/workShops.dart
Labels: better-code

#131 Feature/119 120 127 navigation enhancement
  lib/models/pages.dart
  lib/providers/selectedPage.dart
  lib/screens/about.dart
  lib/screens/home.dart
  lib/screens/info.dart
  lib/screens/newHome.dart
  lib/screens/ngGirls.dart
  lib/screens/schedule.dart
  lib/screens/speakers.dart
  lib/screens/workShops.dart
  lib/widgets/drawer.dart
  lib/widgets/home/button.dart
  lib/widgets/home/tabs.dart
  lib/widgets/newHome/events.dart
Labels: enhancement

#141 Fixed fetch local data when the user is online
  assets/images/authors/danielmichalak.jpg
  lib/main.dart
  lib/providers/eventItems.dart
  lib/providers/infoItems.dart
  lib/providers/ngGirls.dart
  lib/providers/speakers.dart
  lib/providers/workShops.dart
  lib/screens/info.dart
  lib/screens/ngGirls.dart
  lib/screens/schedule.dart
  lib/screens/speakers.dart
  lib/screens/workShops.dart
  lib/services/contentful.dart
  lib/shared/widgets/animatedBottomNav.dart
  lib/shared/widgets/emptyListInformation.dart
  lib/widgets/connection.dart
  lib/widgets/info/content.dart
  lib/widgets/ngGirls/content.dart
  lib/widgets/schedule/content.dart
  lib/widgets/speakers/content.dart
  lib/widgets/workshops/content.dart
Labels: bug
